apps/not_reddit_web/lib/not_reddit_web/router.ex
defmodule NotRedditWeb.Router do
  use NotRedditWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {NotRedditWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug NotRedditWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NotRedditWeb do
    pipe_through :browser

    # get "/", TopicController, :index
    # get "/new", TopicController, :new
    # get "/:id/edit", TopicController, :edit
    # delete "/:id", TopicController, :delete
    # put "/:id", TopicController, :update
    # post "/", TopicController, :create
    # resources "/", TopicController, except: [:show]
    resources "/", TopicController
  end

  scope "/auth", NotRedditWeb do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", NotRedditWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: NotRedditWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

apps/not_reddit_web/lib/not_reddit_web/controllers/auth_controller.ex
defmodule NotRedditWeb.AuthController do
  use NotRedditWeb, :controller
  plug Ueberauth
  alias NotReddit.User
  alias NotReddit.Repo

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, params) do
    user_params = %{token: auth.credentials.token, email: auth.info.email, provider: params["provider"]}
    changeset = User.changeset(%User{}, user_params)
    signin(conn, changeset)
  end

  defp insert_user(changeset) do
    case Repo.get_by(User, email: changeset.changes.email) do
      nil ->
        Repo.insert(changeset)
      user ->
        {:ok, user}
    end
  end

  defp signin(conn, changeset) do
    case insert_user(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Welcome!")
        |> put_session(:user_id, user.id)
        |> redirect(to: Routes.topic_path(conn, :index))
      {:error, _reason} ->
        conn
        |> put_flash(:error, "Something went wrong")
        |> redirect(to: Routes.topic_path(conn, :index))
    end
  end

  def signout(conn,__params) do
    conn
    |> configure_session(drop: true) ## delete anything to do with user session
    |> redirect(to: Routes.topic_path(conn,:index))
  end
end

apps/not_reddit_web/lib/not_reddit_web/controllers/page_controller.ex
defmodule NotRedditWeb.PageController do
  use NotRedditWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

apps/not_reddit_web/lib/not_reddit_web/controllers/topic_controller.ex
defmodule NotRedditWeb.TopicController do
  use NotRedditWeb, :controller
  alias NotReddit.Topic
  alias NotReddit.Repo
  plug NotRedditWeb.Plugs.RequireAuth when action in [:new, :create, :edit, :update, :delete]
  plug :check_topic_owner when action in [:edit, :update, :delete]

  def index(conn, _params) do
    topics =  Repo.all(Topic)

    render conn, "index.html", topics: topics
  end

  def new(conn, _params) do
    changeset = Topic.changeset(%Topic{}, %{})

    render conn, "new.html", changeset: changeset
  end

  def show(conn, %{"id"=> topic_id}) do
    topic = Repo.get!(Topic, topic_id)
    render conn, "show.html", topic: topic
  end

  def create(conn, %{"topic" => topic}) do
    changeset = Topic.changeset(%Topic{}, topic)
    changeset = conn.assigns[:user]
    |> Ecto.build_assoc(:topics)
    |> Topic.changeset(topic)

    case Repo.insert(changeset) do
      {:ok, _post} ->
        conn
        |> put_flash(:info, "Topic Created")
        |> redirect(to: Routes.topic_path(conn, :index))
      {:error, changeset} ->
        conn
        |> put_flash(:error, "Invalid topic name")
        |> render "new.html", changeset: changeset
    end
  end

  def edit(conn, %{"id"=> topic_id}) do
    topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(topic)

    render conn, "edit.html", changeset: changeset, topic: topic
  end

  def update(conn,%{"id"=> topic_id, "topic" => topic}) do
    prev_topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(prev_topic, topic)

    case Repo.update(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic Updated")
        |> redirect(to: Routes.topic_path(conn, :index))
      {:error, changeset} ->
        conn
        |> render "edit.html", changeset: changeset, topic: prev_topic
    end
  end


  def delete(conn, %{"id"=> topic_id}) do
    current_topic = Repo.get!(Topic, topic_id)
    Repo.get!(Topic, topic_id)
    |> Repo.delete!
    %{title: topic_title} = current_topic
    conn
    |> put_flash(:info, "Topic \"#{topic_title}\" Deleted")
    |> redirect(to: Routes.topic_path(conn, :index))

  end

  def check_topic_owner(conn, _params) do
    %{params: %{"id"=> topic_id}} = conn
    if Repo.get(Topic, topic_id).user_id == conn.assigns.user.id do
      conn
    else
      conn
      |> put_flash(:error, "Permission denied")
      |> redirect(to: Routes.topic_path(conn, :index))
      |> halt()
    end
  end
end

apps/not_reddit_web/lib/not_reddit_web/views/error_view.ex
defmodule NotRedditWeb.ErrorView do
  use NotRedditWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/not_reddit_web/lib/not_reddit_web/views/layout_view.ex
defmodule NotRedditWeb.LayoutView do
  use NotRedditWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

apps/not_reddit_web/lib/not_reddit_web/views/page_view.ex
defmodule NotRedditWeb.PageView do
  use NotRedditWeb, :view
end

apps/not_reddit_web/lib/not_reddit_web/views/topic_view.ex
defmodule NotRedditWeb.TopicView do
  use NotRedditWeb, :view
end

apps/not_reddit_web/lib/not_reddit_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

apps/not_reddit_web/lib/not_reddit_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

apps/not_reddit_web/lib/not_reddit_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "NotReddit", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
    <script>
      <%= if @conn.assigns.user do%>
        window.userToken = "<%= Phoenix.Token.sign(NotRedditWeb.Endpoint, "veryUniqueKey", @conn.assigns.user.id) %>"
      <% end %>
    </script>
  </head>
  <body>
    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Not Reddit
        </a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li>
              <%= link "Sign out", to: Routes.auth_path(@conn, :signout) %>
            </li>
          <% else %>
            <li>
              <%= link "Sign in with Github", to: Routes.auth_path(@conn, :request, "github") %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= @inner_content %>
  </body>
</html>

apps/not_reddit_web/lib/not_reddit_web/templates/page/index.html.heex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace of mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.6/CHANGELOG.md">v1.6 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://web.libera.chat/#elixir">#elixir on Libera Chat (IRC)</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
      <li>
        <a href="https://discord.gg/elixir">Elixir on Discord</a>
      </li>
    </ul>
  </article>
</section>

apps/not_reddit_web/lib/not_reddit_web/templates/topic/edit.html.heex
<%= form_for @changeset, Routes.topic_path(@conn, :update, @topic), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title%>
  </div>
  <%= submit "Update", class: "btn btn-primary" %>
<% end %>

apps/not_reddit_web/lib/not_reddit_web/templates/topic/index.html.heex
<h2>Topics</h2>
<ul class="collection">
  <%= for topic <- @topics do %>
    <li class="collection-item">
      <%= link topic.title, to: Routes.topic_path(@conn, :show, topic) %>
      <%= if @conn.assigns.user && @conn.assigns.user.id == topic.user_id do %>
        <div class="right">
          <%= link to: Routes.topic_path(@conn, :edit, topic) do%>
            <i class="material-icons">edit</i>
          <% end %>
          <%= link to: Routes.topic_path(@conn, :delete, topic), method: :delete do%>
            <i class="material-icons">delete</i>
          <% end %>
        </div>
      <% end %> 
    </li>
  <% end %>
</ul>
<div class="fixed-action-btn">
  <%= 
    link to: Routes.topic_path(@conn, :new), 
    class: "btn-floating btn-large waves-effect waves-light red" 
  do %>
    <i class="material-icons">add</i>
  <% end %>
</div>

apps/not_reddit_web/lib/not_reddit_web/templates/topic/new.html.heex
<%= form_for @changeset, Routes.topic_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title%>
  </div>
  <%= submit "Save", class: "btn btn-primary" %>
<% end %>

apps/not_reddit_web/lib/not_reddit_web/templates/topic/show.html.heex
<h5><%= @topic.title %></h5>
<div class="input-field">
  <textarea id="comment-input" id="" cols="30" rows="10" class="materialize-textarea"></textarea>
  <button class="btn" id="add-comment">Add comment</button>
  <ul class="collection" id='comment-section'>
  </ul>
</div>
<script>
  document.addEventListener("DOMContentLoaded",()=>{
    window.createSocket(<%= @topic.id %>)
  })
</script>